# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def movie_app
    pod 'SDWebImage', '~> 5.0'
end

target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  movie_app
 
  # Pods for MovieApp

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppUITests' do
    # Pods for testing
  end

end
